[tool.poetry]
name = "landuse-docs"
version = "0.3"
description = "A package that provides tools for extracting cost recovery method of land use plans in the Netherlands"
authors = ["Babak Firoozi Fooladi <b.firoozi.f@gmail.com>"]
license = "Apache 2.0"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
streamlit = "^1.47.0"
ollama = "^0.5.1"
pandas = "^2.3.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
