FUZZY_TERMS = {
    # "anterieure overeenkomst": "anterior agreement",
    "overeenkomst": "agreement",
    "exploitatieplan": "Exploitation plan",
    "eigendom": "owned",
    "eigenaar": "owner",
    "planschade": "Plan Damage",
    "kosten": "cost",
    # "kavelruilovereenkomst": "parcel exchange agreement",
    # "kostenverhaal": "cost recovery",
    "initiatiefnemer": "initiator",
    # "kosten verzekerd": "insured costs",
    "exploitatie": "exploitation",
    # "grondexploitatie": "land exploitation",
    # "uitvoerbaarheid": "feasibility",
    # "haalbaarheid": "feasibility",
    # "financieel": "financial",
    # "uitvoeringsaspecten": "implementation aspects",
    "bouwclaim": "building claim",
    # "optiecontract": "option contract",
    "verkoopt": "sells",
    "termijn": "deadline",
    "verkopen": "sell",
    "Ruimte voor Ruimte": "Space for Space",
    "grondprijs": "land price",
    "gemeentelijke grond": "municipal land",
    "gronduitgifteprijs": "land issue price",
    "gronduitgifte": "land issue",
    "voorkeursrecht": "Right of first refusal",
    "onteigeningsprocedure": "expropriation procedure",
    "grondverwerving": "land acquisition",
    "onteigening": "expropriation",
    "huurcontract": "lease",
    "'bouwplan'": "building plan",
}
FUZZY_THRESHOLD = 95




MANUAL_QUESTIONS = [
    "Land allocation/sale",
    "Future Agreement",
    "Agreement",
    "Anterior Agreement",
    "Operating Agreement",
    "Plan Damage Agreement",
    "Purchase Agreement",
    "Realisation Agreement",
    "Cooperation Agreement/PPS",
    "Land owned by applicant",
    "Municipality land",
    "Land exploitation Project/scheme",
    "Conservation plan",
    "building plan",
    "Space for Space",
    "Invalid",
]
